name: Update README Repositories

on:
  schedule:
    # Runs once a day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update-Repos-List

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Repos List
        uses: LitoMore/github-profile-repo-list@v1.1.0
        with:
          # Your GitHub username or organization name
          username: 'apexmacworkshop'
          # A personal access token with 'repo' scope
          token: ${{ secrets.GITHUB_TOKEN }}
          # The headline of the repo list
          headline: ' ' # Leaving this blank for a cleaner look
          # The file to update
          readme_path: 'profile/README.md'
          # The template for each repository
          template: '- 🏛️ **[{{repo.name}}]({{repo.html_url}})**: {{repo.description}}'
          # The max number of repositories to list
          max_count: 30
          # The sort key ('pushed', 'created', 'updated', 'full_name')
          sort_by: 'pushed'
          # Repositories to exclude, separated by commas
          exclude_repos: '.github'
